package io.nichijou.oops

internal object OopsPrefsKey {
    const val PREFS_NAME = "oops_signed_theme_prefs"
    const val KEY_THEME = "theme"
    const val KEY_IS_FIRST_TIME = "is_first_time"
    const val KEY_IS_DARK = "is_dark"
    const val KEY_COLOR_ACCENT = "color_accent"
    const val KEY_COLOR_PRIMARY = "color_primary"
    const val KEY_COLOR_PRIMARY_DARK = "color_primary_dark"
    const val KEY_PRIMARY_TEXT_COLOR = "primary_text"
    const val KEY_SECONDARY_TEXT_COLOR = "secondary_text"
    const val KEY_PRIMARY_TEXT_INVERSE_COLOR = "primary_text_inverse"
    const val KEY_SECONDARY_TEXT_INVERSE_COLOR = "secondary_text_inverse"
    const val KEY_WINDOW_BACKGROUND_COLOR = "window_background_color"
    const val KEY_STATUS_BAR_MODE = "status_bar_mode"
    const val KEY_STATUS_BAR_COLOR = "status_bar_color"
    const val KEY_NAV_BAR_COLOR = "nav_bar_color"
    const val KEY_NAV_VIEW_SELECTED_COLOR = "nav_view_selected_color"
    const val KEY_TAB_LAYOUT_TEXT_COLOR = "tab_layout_text_color"
    const val KEY_TAB_LAYOUT_SELECTED_TEXT_COLOR = "tab_layout_selected_text_color"
    const val KEY_BOTTOM_NAV_NORMAL_COLOR = "bottom_nav_normal_color"
    const val KEY_BOTTOM_NAV_SELECTED_COLOR = "bottom_nav_selected_color"
    const val KEY_COLLAPSING_TOOLBAR_DOMINANT_COLOR = "collapsing_toolbar_dominant_color"
    const val KEY_SWIPE_REFRESH_LAYOUT_BACKGROUND_COLOR = "swipe_refresh_layout_background_color"
    const val KEY_SWIPE_REFRESH_LAYOUT_SCHEME_COLORS = "swipe_refresh_layout_scheme_colors"
    const val KEY_TOOLBAR_ICON_COLOR = "toolbar_icon_color"
    const val KEY_TOOLBAR_TITLE_COLOR = "toolbar_title_color"
    const val KEY_TOOLBAR_SUBTITLE_COLOR = "toolbar_subtitle_color"
    const val KEY_SNACK_BAR_TEXT_COLOR = "snack_bar_text_color"
    const val KEY_SNACK_BAR_ACTION_COLOR = "snack_bar_action_text_color"
    const val KEY_SNACK_BAR_BACKGROUND_COLOR = "snack_bar_background_color"
}

