package io.nichijou.oops

const val PREFS_NAME = "io.nichijou.oops.theme_prefs"
const val KEY_THEME = "oops.theme"
const val KEY_IS_FIRST_TIME = "oops.is_first_time"
const val KEY_IS_DARK = "oops.is_dark"
const val KEY_COLOR_ACCENT = "oops.color_accent"
const val KEY_COLOR_PRIMARY = "oops.color_primary"
const val KEY_COLOR_PRIMARY_DARK = "oops.color_primary_dark"
const val KEY_PRIMARY_TEXT_COLOR = "oops.primary_text"
const val KEY_SECONDARY_TEXT_COLOR = "oops.secondary_text"
const val KEY_PRIMARY_TEXT_INVERSE_COLOR = "oops.primary_text_inverse"
const val KEY_SECONDARY_TEXT_INVERSE_COLOR = "oops.secondary_text_inverse"
const val KEY_WINDOW_BACKGROUND_COLOR = "oops.window_background_color"
const val KEY_STATUS_BAR_MODE = "oops.status_bar_mode"
const val KEY_STATUS_BAR_COLOR = "oops.status_bar_color"
const val KEY_NAV_BAR_COLOR = "oops.nav_bar_color"
const val KEY_DISABLE_AUTO_STATUS_BAR_COLOR = "oops.disable_auto_status_bar_color"
const val KEY_DISABLE_AUTO_NAV_BAR_COLOR = "oops.disable_auto_nav_bar_color"
const val KEY_NAV_BAR_DIVIDER_COLOR = "oops.nav_bar_divider_color"
const val KEY_NAV_BAR_MODE = "oops.nav_bar_mode"
const val KEY_NAV_VIEW_SELECTED_COLOR = "oops.nav_view_selected_color"
const val KEY_TAB_LAYOUT_TEXT_COLOR = "oops.tab_layout_text_color"
const val KEY_TAB_LAYOUT_SELECTED_TEXT_COLOR = "oops.tab_layout_selected_text_color"
const val KEY_BOTTOM_NAV_NORMAL_COLOR = "oops.bottom_nav_normal_color"
const val KEY_BOTTOM_NAV_SELECTED_COLOR = "oops.bottom_nav_selected_color"
const val KEY_COLLAPSING_TOOLBAR_DOMINANT_COLOR = "oops.collapsing_toolbar_dominant_color"
const val KEY_SWIPE_REFRESH_LAYOUT_BACKGROUND_COLOR = "oops.swipe_refresh_layout_background_color"
const val KEY_SWIPE_REFRESH_LAYOUT_SCHEME_COLORS = "oops.swipe_refresh_layout_scheme_colors"
const val KEY_TOOLBAR_ICON_COLOR = "oops.toolbar_icon_color"
const val KEY_TOOLBAR_TITLE_COLOR = "oops.toolbar_title_color"
const val KEY_TOOLBAR_SUBTITLE_COLOR = "oops.toolbar_subtitle_color"
const val KEY_SNACK_BAR_TEXT_COLOR = "oops.snack_bar_text_color"
const val KEY_SNACK_BAR_ACTION_COLOR = "oops.snack_bar_action_text_color"
const val KEY_SNACK_BAR_BACKGROUND_COLOR = "oops.snack_bar_background_color"
const val KEY_DEFAULT_COLLAPSING_TOOLBAR_TAG = "oops.default_collapsing_toolbar_tag"

