package io.nichijou.oops

internal object OopsPrefsKey {
    const val PREFS_NAME = "oops_theme_prefs"
    const val KEY_THEME = "theme"
    const val KEY_IS_FIRST_TIME = "is_first_time"
    const val KEY_IS_DARK = "is_dark"
    const val KEY_COLOR_PRIMARY = "color_primary"
    const val KEY_COLOR_PRIMARY_DARK = "color_primary_dark"
    const val KEY_COLOR_ACCENT = "color_accent"
    const val KEY_PRIMARY_TEXT_COLOR = "primary_text"
    const val KEY_SECONDARY_TEXT_COLOR = "secondary_text"
    const val KEY_PRIMARY_TEXT_INVERSE_COLOR = "primary_text_inverse"
    const val KEY_SECONDARY_TEXT_INVERSE_COLOR = "secondary_text_inverse"
    const val KEY_WINDOW_BACKGROUND_COLOR = "window_background_color"
    const val KEY_STATUS_BAR_MODE = "status_bar_mode"
    const val KEY_STATUS_BAR_COLOR = "status_bar_color"
    const val KEY_NAV_BAR_COLOR = "nav_bar_color"
    const val KEY_TAB_LAYOUT_BACKGROUND_MODE = "tab_layout_background_mode"
    const val KEY_TAB_LAYOUT_INDICATOR_MODE = "tab_layout_indicator_mode"
    const val KEY_NAV_VIEW_MODE = "nav_view_mode"
    const val KEY_BOTTOM_NAV_BACKGROUND_MODE = "bottom_nav_background_mode"
    const val KEY_BOTTOM_NAV_ICON_TEXT_MODE = "bottom_nav_icon_text_mode"
    const val KEY_COLLAPSING_TOOLBAR_COLOR = "collapsing_toolbar_color"
    const val KEY_CARD_VIEW_BACKGROUND_COLOR = "card_view_background_color"
    const val KEY_ICON_TITLE_ACTIVE_COLOR = "icon_title_active_color"
    const val KEY_ICON_TITLE_INACTIVE_COLOR = "icon_title_inactive_color"
    const val KEY_SNACK_BAR_TEXT_COLOR = "snack_bar_text_color"
    const val KEY_SNACK_BAR_ACTION_COLOR = "snack_bar_action_text_color"
    const val KEY_SNACK_BAR_BACKGROUND_COLOR = "snack_bar_background_color"
}

